name = "marin-discord-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[[d1_databases]]
binding = "DB"
database_name = "marin-discord"
database_id = "e7bf4268-5fc5-447b-9eba-a4e1ea4003f5"

[dev]
port = 5273

[vars]
CORS_ORIGIN = "*"
