name = "marin-discord-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[[d1_databases]]
binding = "DB"
database_name = "marin-discord"
database_id = "8ca54637-0c8a-42fd-9ffe-5f2f97d3b960"

[dev]
port = 5273

[vars]
CORS_ORIGIN = "*"
GUILD_ID = "1354881461060243556"
ARCHIVE_DB_URL = "https://openathena.s3.amazonaws.com/marin-discord/archive.db"
